spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
file:
  location: F:\\lab-print\\
  pdf-tool:
log:
  duration: /Users/pangjiping/photo/

logging:
  config: classpath:log4j2.xml
server:
  port: 9080