spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
file:
  location: D:\\labprint-test\\
  pdf-tool:
log:
  duration: /Users/pangjiping/photo/

logging:
  config: classpath:log4j2.xml