name: StatusFunction for Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: I'm sleepy
        run: sleep 365d
      - name: I'm always
        if: ${{ always() }}
        run: date +"%Y-%m-%d %H:%M:%S %Z"
      - name: I'm unreachable
        run: echo "I'm unreachable"
